### ISSUE TITLE
Error running steamctl authenticator add

### ISSUE THREAD

**Issue by DaVoodoo** [ValvePython/steamctl#13]
I am running Windows 10. 

I installed Python 3.8 and Cygwin and steam in python and steamctl in python. 

Ultimately I want to create a qrcode to add to my Aegis Autenticator. I have steamguard setup on my phone. I therefore assume that I must add another one using **steamctl authenticator add**? 

Can you please assist? I get the following error when I run the  **steamctl authenticator add** command:
```
    :\Python38\Scripts>steamctl authenticator add --force voodoo_zn
    To add an authenticator, first we need to login to Steam
    Account name: xxxxxxx
    Enter password for 'xxxxxxx':
    Enter 2FA code: PJPDM
    Login successful. Checking pre-conditions...
    Traceback (most recent call last):
      File "c:\python38\lib\runpy.py", line 193, in _run_module_as_main
        return _run_code(code, main_globals, None,
      File "c:\python38\lib\runpy.py", line 86, in _run_code
        exec(code, run_globals)
      File "C:\Python38\Scripts\steamctl.exe\__main__.py", line 7, in <module>
      File "c:\python38\lib\site-packages\steamctl\__main__.py", line 53, in main
        rcode = cmd_func(args=args)
      File "c:\python38\lib\site-packages\steamctl\commands\authenticator\cmds.py", line 121, in cmd_authenticator_add
        sa.add()
      File "c:\python38\lib\site-packages\steam\guard.py", line 180, in add
        raise SteamAuthenticatorError("Failed to add authenticator. Error: %s" % repr(EResult(resp['status'])))
    steam.guard.SteamAuthenticatorError: Failed to add authenticator. Error: <EResult.DuplicateRequest: 29>
```

`

**Comment by rossengeorgiev** [comment]
Hi, there can only be one authenticator configured on a steam account. My guess is the response means there is already an authenticator configured. I'll test that out later.

You will need to remove your current steam guard, which will impose some restrictions on steam account, and run the add command. There will be prompt for whether you want to configure the app in parallel. It should let you have the same guard secrets in steamctl and the phone app.

**Comment by rossengeorgiev** [comment]
Did you set up with steamctl and steam app together? Just curious if it worked.

Great suggestion, a message for that situation is needed

**Comment by DaVoodoo** [comment]
Yes, I did run the setup with steamctl and steam together without a problem.

When you have included the enhancement I will also test for you. ;-)
