### ISSUE TITLE
list games owned without webapi

### ISSUE THREAD

**Issue by varmd** [ValvePython/steamctl#20]
Is it possible to list apps owned without using webapi?

**Comment by rossengeorgiev** [comment]
No. Sounds like a feature request. Are you talking about your own account owned apps, or other accounts?

**Comment by varmd** [comment]
Own account apps. This would allow using steamctl in a similar way to https://github.com/derrod/legendary.

**Comment by rossengeorgiev** [comment]
Interesting project. However, steamctl is not intended to ever be a launcher. Listing apps can be implemented.
