### ISSUE TITLE
Some product_info need authentication

### ISSUE THREAD

**Issue by cirelli94** [ValvePython/steamctl#31]
Hello,
I'm trying to understand if I can completely avoid authentication when I use the command `$ steamctl apps product_info xxxxxxxxxxxxx`.
My goal is to find out the `timeupdated` of the public branch, but some AppID works well some other with `--anonymous`, some others don't with this error:
```
$ steamctl --anonymous apps product_info 1172620 | jq -r .depots.branches.public.timeupdated

[INFO] Attempting anonymous login
[ERROR] No license available for App ID: 1172620 (EResult.AccessDenied)
```

Am I doing this right?
Is there any other way to find out if timeupdate has changed without authentication?

Thanks in advance.

**Comment by rossengeorgiev** [comment]
You cannot "avoid" authentication. You need an account that has a license for the app you are looking up. Anonymous accounts only have access to https://steamdb.info/sub/17906/

**Comment by cirelli94** [comment]
Thank you very much @rossengeorgiev !
