### ISSUE TITLE
[decrypt_gid] Can't parse beta password if it contains letters?

### ISSUE THREAD

**Issue by Nigm4s** [ValvePython/steamctl#39]
![capture](https://user-images.githubusercontent.com/87004034/124557700-3bb06580-de53-11eb-80fe-4b6a219643f7.PNG)
(I did not hide branch password because it's literally public)

**Comment by rossengeorgiev** [comment]
Remove `manifest_gid` from your command

**Comment by Nigm4s** [comment]
![capture2](https://user-images.githubusercontent.com/87004034/124637827-a8ebe700-dea3-11eb-862c-34acb3a525b1.PNG)

**Comment by rossengeorgiev** [comment]
Interesting. I don't why that is failing, and I can't test as I don't own that appid. However, you could modify the file just before line 122 and insert like:

```
print("egid:", repr(encrypted_gid))
print("password:", repr(password))
```
With that I can look to figure out why the output doesn't match the unpack

**Comment by Nigm4s** [comment]
![capture3](https://user-images.githubusercontent.com/87004034/124680375-ae672280-dedf-11eb-9837-29c7d5462480.PNG)

**Comment by rossengeorgiev** [comment]
Ok, looks like that decrypts to empty, which means the password is incorrect. I guess Steam rotates it on the backend, and it changes, so older encrypted gids can no longer be decrypted. I'll add an error message for this
