### ISSUE TITLE
Demo for idle-games

### ISSUE THREAD

**Issue by soulkirito** [ValvePython/steamctl#53]
![image](https://user-images.githubusercontent.com/66830063/176850265-1f91bc49-1c81-4627-9340-fdc76686d9db.png)
Not sure whether it is working or not.
I checked the playing time of the particular game in steam launcher didn't increase tho

**Comment by rossengeorgiev** [comment]
The account needs to own the app as the command currently doesn't verify if the account has a license for the app.
