### ISSUE TITLE
[FEATURE REQUEST] Password argument

### ISSUE THREAD

**Issue by Aida-Enna** [ValvePython/steamctl#56]
**Is your feature request related to a problem? Please describe.**
Hello! I use this program as part of a server script to check for updates to a game - I put in my user password the first time and it loads it fine from then on... but after an uncertain amount of time, it "forgets" the password and requires manually inputting it in again. Is there any way I can enter the password via command line?

**Describe the solution you'd like**
Being able to enter the password for the account via the command line, like the -user flag.

**Comment by nutterthanos** [comment]
depotdownloader already has this as a feature

**Comment by Aida-Enna** [comment]
Yeah, but I can't have it just output the latest Manifest ID like I can with this program. This program does exactly what I need, aside from the password flag.

**Comment by nutterthanos** [comment]
> Yeah, but I can't have it just output the latest Manifest ID like I can with this program. This program does exactly what I need, aside from the password flag.

👍

**Comment by rossengeorgiev** [comment]
Yes, this is seem needed in some form. If you input your password by providing it via an argument then it also ends up logs, which is not great. A way to avoid that is to allow use of environemental variables to set these and other arguments.

**Comment by nutterthanos** [comment]
> Yes, this is seem needed in some form. If you input your password by providing it via an argument then it also ends up logs, which is not great. A way to avoid that is to allow use of environemental variables to set these and other arguments.

but can't people just hide it/redact it when they need to share the log?

**Comment by rossengeorgiev** [comment]
Not the program log, but stuff like `bash_history`, sudo logs, or other. It is bad practice to pass password as argument
