### ISSUE TITLE
[BUG] (EResult.Fail) Failed to login: <EResult.Fail: 2>

### ISSUE THREAD

**Issue by switchuwu** [ValvePython/steamctl#60]
Happens every time i try to use any option when logged in

C:\Users\switchuwu>steamctl -l debug depot info --app 730
[DEBUG] steamctl: Parsed args: {'versions_report': None, 'log_level': 'debug', 'anonymous': False, 'user': None, 'command': 'depot', '_cmd_func': 'steamctl.commands.depot.gcmds:cmd_depot_info', 'subcommand': 'info', 'cell_id': None, 'os': 'any', 'file': None, 'app': 730, 'depot': None, 'manifest': None, 'branch': 'public', 'password': None, 'skip_depot': None, 'skip_login': False, 'skip_licenses': False}
[DEBUG] SteamClient: Reading CM servers from 'C:\\Users\\switchuwu\\AppData\\Local\\steamctl\\steamctl\\client\\cm_servers.json'
[DEBUG] CMServerList: Added 80 new CM addresses.
[DEBUG] steamctl.utils.storage: Opening file (r): C:\Users\switchuwu\AppData\Local\steamctl\steamctl\cs_servers.json
[DEBUG] CachingCDNClient: No steam licenses found on SteamClient instance
[DEBUG] steamctl.utils.storage: Opening file (r): C:\Users\switchuwu\AppData\Local\steamctl\steamctl\client\lastuser
[INFO] SteamClient: Reusing previous username: <Username>
[INFO] SteamClient: Hint: use 'steamctl --user <username> ...' to change
[DEBUG] steamctl.utils.storage: Opening file (r): C:\Users\switchuwu\AppData\Local\steamctl\steamctl\client\lastuser
[INFO] SteamClient: Attempting login with remembered credentials
[DEBUG] steamctl.utils.storage: Opening file (r): C:\Users\switchuwu\AppData\Local\steamctl\steamctl\client\<Username>.key
[DEBUG] SteamClient: Re-login result is: <EResult.Fail: 2>
[ERROR] steamctl.commands.depot.gcmds: (EResult.Fail) Failed to login: <EResult.Fail: 2>

**Comment by rossengeorgiev** [comment]
This is most likely a result of https://github.com/ValvePython/steam/issues/408

I've pushed a new version of `steam`, can you update and retry? You may need to login once for it to pick up a new loginkey.

**Comment by switchuwu** [comment]
yep, works now
thank you!
