### ISSUE TITLE
Steamctl does not like to run in the background/process

### ISSUE THREAD

**Issue by NethercraftMC5608** [ValvePython/steamctl#70]
I am making a script in python, and it uses subprocess.popen (which would run it in the background)

It works when i run it in the terminal, but once i make the script start on boot, steamctl would not work with subprocess.

I would love to give you debug logs, but i cannot seem to access or get the output of the python script running (as i am running it headlessly)

**Comment by nutterthanos** [comment]
Maybe have the script pipe it's output to a file

**Comment by NethercraftMC5608** [comment]
> Maybe have the script pipe it's output to a file

I have tried that, doesn't work and does not output error from subprocess. 

But i've now just built it from the ground up using the steam library.
